print("Nhập vào giá trị của a")
a = input("a = ")
a = int(a)
print("Nhập vào giá trị của b")
b = input("b = ")
b = int(b)

print("{0}+{1}={2}".format(a, b, a + b))
print("{0}-{1}={2}".format(a, b, a - b))
print("{0}*{1}={2}".format(a, b, a * b))
print("{0}/{1}={2}".format(a, b, a / b))
print("{0}%{1}={2}".format(a, b, a % b))
print("{0}**{1}={2}".format(a, b, a**b))
print("{0}//{1}={2}".format(a, b, a // b))
